# Generated by Django 3.2.17 on 2023-02-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
