# Generated by Django 3.2.17 on 2023-02-27 05:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_blog', '0003_auto_20230224_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/ddfkccacb/image/upload/t_Grayscale/v1675254029/media/post_pics/sample.jpg', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='media/profile_pics/vsquvarj1tbivkaoe1vr.jpg', max_length=255, null=True, verbose_name='image'),
        ),
    ]
