# Generated by Django 3.2.17 on 2023-02-19 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_blog', '0004_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
